### ISSUE TITLE
http://com.orange/wro/taglib cannot be resolved

### ISSUE THREAD

**Issue by simoami** [Orange-OpenSource/wro4j-taglib#1]
Hello,

The use of the jsp  taglib causes the following error :

The absolute uri: http://com.orange/wro/taglib cannot be resolved in either web.xml or the jar files deployed with this application

The taglib:
<%@ taglib uri="http://com.orange/wro/taglib" prefix="wro" %>

Any ideas?

**Comment by julienw** [comment]
you're right, the example has an error, the correct uri is http://orange.com/wro/taglib.
