### ISSUE TITLE
use without maven

### ISSUE THREAD

**Issue by zepernick** [Orange-OpenSource/wro4j-taglib#17]
I am using wro4j at runtime only and am looking for a solution to toggle between my combined file in production and importing individual css/js in development for debugging.  This project looks like it comes close to what I need.  Am I able to use it without having first merged the files using Maven?  Trying to figure out if I need to create a separate taglib for my needs.

**Comment by julienw** [comment]
I think you should be able to do it using plain wro4j.

**Comment by zepernick** [comment]
Thanks, you can turn off minification, but I could not find a way to break it out into separate files.  I created my own tag that seems to be working out.

**Comment by julienw** [comment]
good :) I can't close this issue because I'm not part of this project (anymore ;) ), can you do it ?
