### ISSUE TITLE
Documentation for OptionalScript

### ISSUE THREAD

**Issue by simoami** [Orange-OpenSource/wro4j-taglib#4]
Hello,
The description for this tag specifies when and how to use it but does not describe its function. It would be good to update the description to something like:

optionalScript: (optional), does something ..... Note: it should only be used when LESS is used with exploded files. It should be included AFTER the stylesheets and inside the header.

**Comment by bidorffOL** [comment]
The README.md has been updated, the description is now :

optionalScript: (optional) generates script tags which were deemed necessary by wro4j-taglib (an example would the inclusion of less.js when exploded LESS stylesheets are included). NOTE: This tag should always be the last one of the header.

**Comment by simoami** [comment]
Thank you!
