### ISSUE TITLE
IndexOutOfBoundsException in WroConfig.java (line117)

### ISSUE THREAD

**Issue by simoami** [Orange-OpenSource/wro4j-taglib#5]
When specifying the following config properties in the wro4j-maven-plugin:

```
<jsDestinationFolder>${project.build.directory}/${project.build.finalName}/bundles/js/</jsDestinationFolder>
<cssDestinationFolder>${project.build.directory}/${project.build.finalName}/bundles/css/</cssDestinationFolder>
```

The taglib fails with an IndexOutOfBoundsException in WroConfig.java (line 117):

```
String groupName = basename.substring(0, basename.lastIndexOf('-'));
```

It happens because resourcePaths enumerates folder names ["bundles/css","bundles/js"], so  basename.lastIndexOf('-') returns -1 resulting in basename,substring(0, -1) hence the exception.

Can this be fixed to support bundle subfolders? Maybe you could add support for 2 additional context parameters to support js and css resources:

```
<param-name>com.orange.wro.base.jspath</param-name>
<param-name>com.orange.wro.base.csspath</param-name>
```

Thanks for the great taglib!

**Comment by bidorffOL** [comment]
I'm sorry for the delay, I forgot to watch the project and I missed the bug requests for a while.

It seems that WroConfig is generating quite a lot of problems (see bug #6). I'll give it a look next week as I would like to merge bug #7 before (this pull request changes quite a lot of code in WroConfig).
