### ISSUE TITLE
taglib seeks to resolve wildcards even if exploded is false

### ISSUE THREAD

**Issue by simoami** [Orange-OpenSource/wro4j-taglib#6]
Hi David,

We package our app into a war and deploy it. The package includes all the minified bundles but excludes the source files. we don't need sources in QA and production environments.

When deployed, the app runs as expected and the JS bundles are served as expected, but the logs are being filled up with warnings as wro4j attempts to resolve some wildcards in our wro group definitions and does't find the corresponding sources. This is not necessary when the taglib is configured with exploded=false.

I think this happens when you invoke wro4j and create an instance of the wroModel. It might be indirectly triggered from:
helper.getManagerFactory().create().getModelFactory().create();

Here's a subset of the log:

``` logs
DEBUG  (JCLLoggerAdapter.java:188) - Expanding resource: /javascript/ga/*.js
DEBUG  (JCLLoggerAdapter.java:188) - computeBaseNameFolder for resource ro.isdc.wro.model.resource.Resource@343947c[JS,/javascript/ga/*.js,true]
DEBUG  (JCLLoggerAdapter.java:188) - resourcePath: /javascript/ga/**
DEBUG  (JCLLoggerAdapter.java:188) - locate resource: /javascript/ga/**
WARN   (JCLLoggerAdapter.java:379) - [FAIL] localize the stream containing wildcard. Original error message: 'Invalid folder provided, with path: /workspace/trunk/dashboard/web/target/project-web-4-SNAPSHOT/javascript/ga, with fileNameWithWildcard: /javascript/ga/**".
 Trying to locate the stream without the wildcard.'
```

Note: the debug statements are to help understand where it's failing. But it's the WARN entries I'm after.

**Comment by bidorffOL** [comment]
I just took a look at this issue, I think I found a way to fix it. However, I won't be able to do it until next week and I would like to merge bug #7 before as it will change a lot of code in the faulty classes.

**Comment by simoami** [comment]
Hi David, any updates on this?

**Comment by bidorffOL** [comment]
The taglib should now be seeking the necessary files when needed, therefore, if exploded is set to false, it should not be looking for the exploded files
